version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - "./:/app"
    links:
      - redis
      - postgres
    env_file:
      - .env

  sshd:
    build:
      context: .
      dockerfile: ./compose/sshd/Dockerfile
    ports:
      - "22:22"
    volumes:
      - "./app/ssh_directory:/root"

  app_consumer:
    build:
      context: .
      dockerfile: ./compose/app_consumer/Dockerfile
    volumes:
      - "./:/app"
    links:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    build: ./compose/postgres
    ports:
        - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
