"""
Django settings for lazacom3pl project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from .base import *

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# for now, not using database functionality
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'lazacom3pl',
#         # The following settings are not used with sqlite3:
#         'USER': 'postgresuser',
#         'PASSWORD': 'mysecretpass',
#         'HOST': 'postgres',  # Empty for localhost through domain sockets or
#                                #  '127.0.0.1' for localhost through TCP.
#         'PORT': '5432',  # Set to empty string for default.
#         'ATOMIC_REQUESTS': True,
#     }
# }


CACHES = {
   "default": {
       "BACKEND": "django_redis.cache.RedisCache",
       "LOCATION": "redis://redis:6379/2",
       "OPTIONS": {
           "CLIENT_CLASS": "django_redis.client.DefaultClient",
           "SOCKET_CONNECT_TIMEOUT": 10,  # in seconds
           "SOCKET_TIMEOUT": 10,  # in seconds
           "IGNORE_EXCEPTIONS": True,
       }
   },
   "JWT_AUTH_CACHE": {
       "BACKEND": "django_redis.cache.RedisCache",
       "LOCATION": "redis://redis:6379/3",
       "OPTIONS": {
           "CLIENT_CLASS": "django_redis.client.DefaultClient",
           "SOCKET_CONNECT_TIMEOUT": 10,  # in seconds
           "SOCKET_TIMEOUT": 10,  # in seconds
           "IGNORE_EXCEPTIONS": True,
       }
   },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'public/static/')
